### PR TITLE
add newer versions of node and python

### PR DESCRIPTION
**Pull request by flatsiedatsie**

### CODE REVIEW

**Comment by flatsiedatsie** [comment]
- adds Node 16 and 18
- updates python 3.9
- adds Python 3.10 and 3.11
- changes Buster to Bullseye

**Comment by flatsiedatsie** [comment]
Note: I did not update NVM version

**Comment by benfrancis** [comment]
@tim-hellhake Is this going to cause any problems for existing gateways which are stuck on buster and Node 10 for the time being?

**Comment by benfrancis** [comment]
@flatsiedatsie I'm not sure you meant to add those last two commits? [ecd8683](https://github.com/WebThingsIO/addon-builder/pull/58/commits/ecd86831e4674f09c4b24b00190f68c375b12270), [28d2fe6](https://github.com/WebThingsIO/addon-builder/pull/58/commits/28d2fe698874a5a4025df96f8e0fdc41cc3485b2).

Have you tested add-ons built with this toolchain on WebThings Gateway 1.1? My main concern is whether building under bullseye will cause any problems for gateways still running buster.

**Comment by flatsiedatsie** [comment]
No I did not. Weird.

**Comment by flatsiedatsie** [comment]
I t seems I have no idea how to undo it :-D

**Comment by benfrancis** [comment]
> I t seems I have no idea how to undo it :-D

I'm guessing from your commit messages that you're using some kind of GUI-based git client, but this might be a good opportunity to learn how to use [`git rebase`](https://git-scm.com/docs/git-rebase) to drop commits from a branch :)

**Comment by flatsiedatsie** [comment]
Yes I'm a GUI user :-)

*ducks under table

Because this wasn't happening I found a way around using the pre-built docker images. I [created a Github workflow](https://github.com/createcandle/matter-adapter/blob/main/.github/workflows/release.yml) that (as far as I know..) does the same thing. It caches the images on Github instead.

I'd prefer to use the Webthings flow so that our projects remain optimally compatible. But I don't have the time or desire to dive into github command line (I tried earlier.. not my cup of tea).

Can this PR perhaps be fixed from "your end"?

**Comment by tim-hellhake** [comment]
> use any problems for existing gateways which are stuck on buster and Node 10 for the time being?

Adding new node/python versions shouldn't be a problem but I'm not so sure about upgrading to buster.
It might break some native dependencies.

**Comment by benfrancis** [comment]
> I'm not so sure about upgrading to bullseye.
It might break some native dependencies.

That's my concern too. Apart from needing to remove the extraneous commits, this change would need some extensive testing to ensure it doesn't cause add-ons to stop working on existing gateways.

**Comment by flatsiedatsie** [comment]
Alright, it sounds like it's best to just close this PR for now.

**Pull request closed without merging**
